---
sudo: false
language: ruby
cache: bundler
branches:
  only:
  - master
rvm:
- 2.4.10
- 2.5.8
- 2.6.6
- 2.7.1
- ruby-head
before_install: gem install bundler -v 2.1.4
script: bundle exec rake test:unit
