module Jam
  autoload :CLI, "jam/cli"
  autoload :Commands, "jam/commands"
  autoload :Error, "jam/errors"
  autoload :Framework, "jam/framework"
  autoload :Path, "jam/path"
  autoload :Paths, "jam/paths"
  autoload :Plugin, "jam/plugin"
  autoload :Plugins, "jam/plugins"
  autoload :Remote, "jam/remote"
  autoload :Result, "jam/result"
  autoload :ShellCommand, "jam/shell_command"
  autoload :TaskLibrary, "jam/task_library"
  autoload :VERSION, "jam/version"
end
