name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build_docs:
    name: "Build Docs"
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: mkdocs build
  rubocop:
    name: "Rubocop"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
          bundler-cache: true
      - run: bundle exec rubocop
  test:
    name: "Test / Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.1", "3.2", "3.3", "3.4", "head"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: git config --global user.name 'github-actions[bot]'
      - run: git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - run: bundle exec rake test
  test_rails_deploy:
    name: "Test / Rails Deploy"
    runs-on: ubuntu-latest
    needs: [rubocop, test]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
          bundler-cache: true
      - run: bundle exec rake test:e2e
